from sklearn import tree
import pandas as pd
import unidecode
df = pd.read_excel('./dataset.xlsx')



def makeDict(input_list):
    temp_dict = dict({"nan": -1})
    index = 0
    for value in input_list:
        if index == 0:
            temp_dict[unidecode.unidecode(value).lower()] = -1
        else:
            temp_dict[unidecode.unidecode(value).lower()] = index
        index = index + 1
    return temp_dict


column_departamento = [
"nan",
"Piura",
"Lima",
"Junín",
"Áncash",
"Ucayali",
"Arequipa",
"San Martín",
"Callao",
"Tumbes",
"Loreto",
"Huancavelica",
"La Libertad",
"Puno",
"Lambayeque",
"Pasco",
"Tacna",
"Huánuco",
"Cusco",
"Cajamarca",
"Apurímac",
"Moquegua",
"Amazonas",
"Ayacucho",
"Madre de Dios"
]

column_provincia = [
"nan",
"Piura",
"Lima",
"Satipo",
"Huaraz",
"Coronel Portillo",
"Arequipa",
"Moyobamba",
"Prov. Const. del Callao",
"Zarumilla",
"Maynas",
"San Martín",
"CHINCHA",
"Trujillo",
"Alto Amazonas",
"Bellavista",
"San Román",
"Santa",
"Concepción",
"Chiclayo",
"Barranca",
"Chanchamayo",
"Oxapampa",
"Morropón",
"Huancayo",
"Rioja",
"Tacna",
"Cañete",
"Huancavelica",
"Leoncio Prado",
"Cusco",
"Huaura",
"Picota",
"Huallaga",
"Huánuco",
"Cajamarca",
"Ambo",
"Islay",
"Mariscal Cáceres",
"PISCO",
"El Dorado",
"Abancay",
"Sullana",
"Chucuito",
"Lambayeque",
"Mariscal Nieto",
"Ilo",
"Pacasmayo",
"Huaral",
"Celendín",
"Pasco",
"San Ignacio",
"Camaná",
"Tumbes",
"Utcubamba",
"Huamanga",
"Atalaya",
"Chepén",
"Junín",
"Contralmirante Villar",
"Pachitea",
"Andahuaylas",
"Jaén",
"Virú",
"Puno",
"Paita",
"Anta",
"Canta",
"Tambopata",
"Chupaca",
"Talara",
"Huarmey",
"Canchis",
"PALPA",
"El Collao",
"Huarochirí",
"Huaylas",
"Puerto Inca",
"Ferreñafe",
"Tarma",
"Casma",
"Ascope",
"Cutervo",
"Sechura",
"Yauli",
"Padre Abad",
"Huamalíes",
"San Marcos",
"Requena",
"NAZCA",
"Espinar",
"Carhuaz",
"Urubamba",
"Calca",
"Caylloma",
"CALLAO",
"Acomayo",
"Huanta",
"Lamas",
"Chota",
"Loreto",
"La Convención",
"Oyón",
"Hualgayoc",
"Yungay",
"Sánchez Carrión",
"Tayacaja",
"Bagua",
"Castilla",
"Tocache",
"Caravelí",
"La Mar",
"Cotabambas",
"Corongo",
"Huari",
"Cajabamba",
"Azángaro",
"Daniel Alcides Carrión",
"Otuzco",
"Datem del Marañón",
"Bolognesi",
"Recuay",
"Ocros",
"Gran Chimú",
"Chachapoyas",
"Tarata",
"Lauricocha",
"Jauja",
"Lampa",
"Pallasca",
"Mariscal Ramón Castilla",
"Quispicanchi",
"Jorge Basadre",
"Sucre",
"Tahuamanu",
"Melgar",
"Sihuas",
"Paucartambo",
"Rodríguez de Mendoza",
"Bongará",
"Ucayali"
]

column_distrito = [
"nan",
"Veintiseis de Octubre",
"Surquillo",
"Satipo",
"Santiago de Surco",
"Lima",
"San Borja",
"San Juan de Miraflores",
"Huaraz",
"Barranco",
"La Victoria",
"Ate",
"Calleria",
"Miraflores",
"José Luis Bustamante Y Rivero",
"Moyobamba",
"Cayma",
"Bellavista",
"Zarumilla",
"Chorrillos",
"Callao",
"Iquitos",
"Magdalena del Mar",
"San Juan de Lurigancho",
"Comas",
"Morales",
"CHINCHA",
"La Esperanza",
"La Molina",
"Yurimaguas",
"Jesús María",
"San Rafael",
"San Isidro",
"Juliaca",
"San Miguel",
"Trujillo",
"Chimbote",
"Yarinacocha",
"Punta Negra",
"Pueblo Libre",
"Carabayllo",
"Matahuasi",
"Puente Piedra",
"José Leonardo Ortiz",
"Breña",
"Supe",
"Pichanaqui",
"Santa Anita",
"Tambo Grande",
"Piura",
"Nuevo Chimbote",
"Villa Rica",
"Chulucanas",
"Tarapoto",
"Los Olivos",
"San Luis",
"Lince",
"Castilla",
"Villa María del Triunfo",
"Huancayo",
"Posic",
"Chiclayo",
"Rímac",
"Chanchamayo",
"Tacna",
"Lurin",
"La Banda de Shilcayo",
"Yura",
"San Vicente de Cañete",
"Huancavelica",
"Rupa -Rupa",
"Cieneguilla",
"Yanahuara",
"Lurigancho",
"San Antonio",
"San Martín de Porres",
"Arequipa",
"Cusco",
"Santa María del Mar",
"Santa Rosa",
"Huacho",
"ICA",
"Picota",
"Saposoa",
"Amarilis",
"Florencia de Mora",
"Huanuco",
"La Perla",
"El Tambo",
"Sachaca",
"Cajamarca",
"Villa El Salvador",
"Tomay Kichwa",
"Cerro Colorado",
"Campoverde",
"Cocachacra",
"Juanjuí",
"Chaclacayo",
"PISCO",
"Calzada",
"Victor Larco Herrera",
"San Jerónimo",
"San José de Sisa",
"Pilcomayo",
"Abancay",
"Sullana",
"Punchana",
"Desaguadero",
"Lambayeque",
"Pachacamac",
"Pucusana",
"Motupe",
"Saña",
"Moquegua",
"Ilo",
"Wanchaq",
"San José",
"Huanchaco",
"Ventanilla",
"Mala",
"Chancay",
"Nueva Cajamarca",
"Rioja",
"Salitral",
"Vegueta",
"Huaral",
"Celendín",
"Bajo Biavo",
"Punta Hermosa",
"Manantay",
"Yanacancha",
"Tucume",
"San José de Lourdes",
"Asia",
"Samuel Pastor",
"El Agustino",
"Catacaos",
"Aguas Verdes",
"Tumbes",
"San Bartolo",
"Chilca",
"Bagua Grande",
"Ayacucho",
"Raymondi",
"Jayanca",
"Santa María",
"San Sebastian",
"Chepen",
"Junin",
"Chaupimarca",
"Imperial",
"Cerro Azul",
"Paucarpata",
"Zorritos",
"San Hilarión",
"Independencia",
"San Juan Bautista",
"Paramonga",
"Panao",
"Andahuaylas",
"Jaén",
"Huaura",
"Carmen Alto",
"Moche",
"Los Baños del Inca",
"Barranca",
"Characato",
"Marcavelica",
"Viru",
"Puno",
"Miguel Checa",
"Paita",
"Supe Puerto",
"Cachimayo",
"Simbal",
"San Ramón",
"Nuevo Imperial",
"Canta",
"Elías Soplin Vargas",
"Tambopata",
"Laredo",
"Pimentel",
"Samegua",
"Pangoa",
"Mazamari",
"Chupaca",
"El Alto",
"Coronel Gregorio Albarracín Lanchipa",
"Belén",
"La Huaca",
"Huarmey",
"Socabaya",
"Sicuani",
"PALPA",
"Pariñas",
"Ilave",
"Pacanga",
"San Jerónimo de Tunan",
"Santa María del Valle",
"Hualmay",
"La Punta",
"Caraz",
"Concepción",
"Santiago",
"Puerto Inca",
"Pacasmayo",
"Chipurana",
"Ferreñafe",
"Santa Eulalia",
"Tarma",
"Camaná",
"Jacobo Hunter",
"Casma",
"Alto Selva Alegre",
"Ascope",
"El Porvenir",
"Cutervo",
"Antioquia",
"Alto de la Alianza",
"Huarochiri",
"San Pedro de Lloc",
"Sechura",
"Santa Cruz de Flores",
"Ancón",
"Yauli",
"Río Negro",
"Padre Abad",
"Llata",
"Oxapampa",
"Mariano Melgar",
"Perene",
"Chao",
"Pedro Gálvez",
"La Joya",
"Jangas",
"Pillco Marca",
"La Matanza",
"Reque",
"Guadalupe",
"Anta",
"Mejia",
"Requena",
"NAZCA",
"Ricardo Palma",
"Sapallanga",
"Espinar",
"Comandante Noel",
"Salaverry",
"Sayan",
"Tamburco",
"Yungar",
"Pocollay",
"Pucara",
"Irazola",
"Urubamba",
"Calca",
"Santiago de Cao",
"Aucallama",
"Olmos",
"Mollebaya",
"Chivay",
"Morropon",
"Cajaruro",
"Pardo Miguel",
"Alto Biavo",
"Santa",
"Mosoc Llacta",
"Uchumayo",
"Huanta",
"Poroy",
"Carmen de la Legua Reynoso",
"Caynarachi",
"Sabandia",
"Chota",
"Calango",
"Buenos Aires",
"Monsefu",
"Trompeteros",
"Coishco",
"Quellouno",
"Sacanche",
"Tiabaya",
"Oyon",
"Las Lomas",
"Chontabamba",
"San Fernando",
"La Oroya",
"Juan Guerra",
"Cayalti",
"Santa Ana",
"Bambamarca",
"Yungay",
"Nueva Requena",
"Mollendo",
"Soritor",
"Luyando",
"Paijan",
"Huancan",
"Quilmana",
"Echarate",
"Coayllo",
"Huamachuco",
"San Pablo",
"Pacocha",
"Tres de Diciembre",
"Ollantaytambo",
"Yantalo",
"Yuracyacu",
"Chicama",
"Pampas",
"Carhuaz",
"Bagua",
"Sama",
"Uraca",
"Majes",
"Barranquita",
"Nuevo Progreso",
"José Crespo y Castillo",
"Juli",
"Machupicchu",
"Campanilla",
"Rázuri",
"Chala",
"Los Organos",
"Morococha",
"Awajun",
"Puerto Bermúdez",
"Chongoyape",
"Lamas",
"La Unión",
"Pativilca",
"Palcazu",
"Oyotun",
"Río Tambo",
"Challhuahuacho",
"San Martín",
"Tambillo",
"Calana",
"La Cruz",
"La Pampa",
"Eten Puerto",
"Chavin de Huantar",
"Marcara",
"Tocache",
"Mochumi",
"Acopampa",
"Colan",
"Caspisapa",
"Pucacaca",
"Huancabamba",
"Huallaga",
"Chocope",
"Cacatachi",
"Condebamba",
"Matacoto",
"Encañada",
"Mariscal Cáceres",
"Alto Nanay",
"Azángaro",
"Huamancaca Chico",
"Pueblo Nuevo",
"Sicaya",
"Yanahuanca",
"Morrope",
"Vicco",
"Canoas de Punta Sal",
"Jequetepeque",
"Mito",
"Cajabamba",
"Constitución",
"Ocoña",
"Honoria",
"Otuzco",
"Corrales",
"Tinco",
"Poroto",
"Uchiza",
"Vice",
"Tingo de Ponasa",
"Huallanca",
"Ticapampa",
"Cochas",
"Cascas",
"San Agustín",
"Chachapoyas",
"Jesús Nazareno",
"Tarata",
"Pucyura",
"Churubamba",
"ALTO AMAZONAS",
"Recuay",
"Palca",
"Llacanora",
"Mancos",
"Huayllay",
"Orcotuna",
"Huariaca",
"Corongo",
"La Arena",
"Lunahuana",
"Maras",
"Chinchero",
"Llaylla",
"Castillo Grande",
"Talavera",
"Caminaca",
"Sivia",
"San Miguel de Cauri",
"Jauja",
"Jesús",
"Yuyapichis",
"Pomalca",
"Santa Cruz de Cocachacra",
"Calapuja",
"Acobamba",
"Matucana",
"Mancora",
"Vitoc",
"Tauca",
"Nauta",
"Islay",
"Eten",
"Pilluana",
"Ramón Castilla",
"Santa Rosa de Sacco",
"Pisac",
"Oropesa",
"Locumba",
"Habana",
"Querobamba",
"Ignacio Escudero",
"Santa Rita de Siguas",
"Taray",
"Las Piedras",
"Iñapari",
"Andahuaylillas",
"Polvora",
"Acos",
"Lamay",
"Pacora",
"Tambo",
"Querecotillo",
"Ciudad Nueva",
"Huaylas",
"Ahuac",
"Curimana",
"Nepeña",
"Carhuamayo",
"Ayaviri",
"Illimo",
"Ambo",
"Ayna",
"Indiana",
"Cura Mori",
"Pampa Hermosa",
"San Ignacio",
"Buena Vista Alta",
"Chiguata",
"Santo Domingo de Los Olleros",
"Sihuas",
"Caracoto",
"Rumisapa",
"Kosñipata",
"Tarica",
"Manuel Antonio Mesones Muro",
"Guadalupito",
"San Salvador",
"Huata",
"Pachia",
"Hualhuas",
"Orcopampa",
"Curahuasi",
"Culebras",
"San Nicolás",
"Jazan",
"Contamana"
]
column_categoria = [
"nan",
"Vivienda Unifamiliar",
"Departamento",
"Oficina",
"Local Comercial",
"AVALUOS_TIPOS_INMUEBLE_VEHICULO",
"Almacén /Taller",
"Estacionamiento/depósito (U.I.)",
"Industria",
"Terreno Urbano",
"Centro de Salud",
"Hotel",
"Intitución Educativa",
"Fundo Agrícola",
"Terreno Rústico (eriazo)",
"Muebles y enseres",
"Maquinaria y/o Equipo"
]

column_condicion = [
"nan",
"En construcción",
"Bueno",
"Regular",
"Muy bueno",
"En proyecto",
"Malo",
"Bueno - Regular",
"Regular - Malo"
]

column_metodo_representado = [
"nan",
"Costos o reposición (directo)",
"Comparación de mercado (directo)",
"Renta o capitalización (indirecto)"
]
column_departamento = makeDict(column_departamento)
column_provincia = makeDict(column_provincia)
column_distrito = makeDict(column_distrito)
column_categoria = makeDict(column_categoria)
column_condicion = makeDict(column_condicion)
column_metodo_representado = makeDict(column_metodo_representado)



# print(column_departamento)
def formatInput(input_list):
    for index, value in enumerate(input_list):
        value = unidecode.unidecode(str(value)).lower()
        if value in column_departamento:
            input_list[index] = column_departamento[value]
        elif value in column_provincia:
            input_list[index] = column_provincia[value]
        elif value in column_distrito:
            input_list[index] = column_distrito[value]
        elif value in column_categoria:
            input_list[index] = column_categoria[value]
        elif value in column_condicion:
            input_list[index] = column_condicion[value]
        elif value in column_metodo_representado:
            input_list[index] = column_metodo_representado[value]
    return input_list



data_values = []
data_classes = []
for i in range(0, df.shape[0]): #desde la fila 0 hasta el tamaño de fila
    row = df.loc[i].values.tolist()
    row = formatInput(row)
    data_values.append(row[1:-1])
    data_classes.append(row[-1])


clf = tree.DecisionTreeClassifier()
clf = clf.fit(data_values, data_classes)

# print("===============================================================")



input_data = [1.0, "nan", 'Piura', 'Piura', 'Veintiseis de Octubre', "nan", "nan", -5.163182, -80.682388, 'Vivienda Unifamiliar', "nan", "nan", 0.0, "nan", 'En construcción', 'Costos o reposición (directo)', 62.50, 27.58]
input_data = formatInput(input_data)
print(input_data)





result = clf.predict([input_data])

print(result)






